spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/rentalapp
    username: postgres
    password: postgres

app:
  cors:
    allowed-origins:
      - http://localhost:3000
  jwt:
    secret: VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JSZW50YWxBcHAxMjM0NTY=
